### ISSUE TITLE
Passing coorelation id from MVC to API

### ISSUE THREAD

**Issue by rajurh** [mderriey/web-api-correlation-id#1]
Is there a way to pass the coorelation id from MVC proj to Web API? Can i have the code snippet for the same please? So that i can tie or group the logs done for request done from UI to API

**Comment by mderriey** [comment]
The way things work in this repository is that the API creates the correlation id and sends it back in the response through an HTTP header.

If you want the UI to create the correlation id and pass it to the API, you could have the API client (the MVC application) add the id to a request header. The API could send use the value of that specific header and add it to the logs accordingly.

To do this, you would have to change [where you source the correlation id from](https://github.com/mderriey/web-api-correlation-id/blob/ca9f9e91dde9473e79800b5f7b68d52aab27648f/src/WebApi.CorrelationId/WebApi.CorrelationId/MessageHandlers/AddCorrelationIdToLogContextHandler.cs#L12). Instead of using the API internal correlation id, you can get it from the request header as mentioned above.
